# Utilizamos una imagen base de Python
FROM python:3.9

# Directorio de trabajo en la imagen
WORKDIR /app

# Copiamos los archivos de la aplicación al directorio de trabajo
COPY . /app

# Instalamos las dependencias de Python desde el archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Aquí puedes agregar cualquier otra configuración o instalación necesaria para tu proyecto

# Exponemos el puerto en el que se ejecutará la aplicación
EXPOSE 8000

# Comando para ejecutar la aplicación cuando el contenedor se inicie
CMD [ "python", "app.py" ]
